# Generated by Django 4.1.2 on 2022-11-18 21:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Isimmmooc_Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre du chapitre', max_length=200)),
                ('video', models.FileField(null=True, upload_to='videos_uploaded/Chapitres', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('presentation', models.TextField(default='Chapitre Presentation', max_length=2000)),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du discipline', max_length=100)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(default='Question Text', max_length=2000)),
                ('number_options', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('type', models.CharField(choices=[('OC', 'One_Choice'), ('MC', 'Multiple_Choice')], default='OC', max_length=2)),
                ('answers', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Item title 2.1'), (2, 'Item title 2.2'), (3, 'Item title 2.3'), (4, 'Item title 2.4'), (5, 'Item title 2.5')], default=1, max_length=3)),
                ('chapitre', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='Isimmmooc_App.chapitre')),
            ],
            options={
                'ordering': ['-question_text'],
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de Cours', max_length=100)),
                ('short_video', models.FileField(null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('description', models.TextField(default='Cours Description', max_length=2000)),
                ('period', models.FloatField(default=1)),
                ('difficulte', models.CharField(choices=[('BG', 'Beginner'), ('MD', 'Intermediate'), ('AV', 'Advanced')], default='BG', max_length=2)),
                ('discipline', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Isimmmooc_App.discipline')),
                ('formateur', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Isimmmooc_Users.formateur')),
            ],
        ),
        migrations.AddField(
            model_name='chapitre',
            name='cours',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Isimmmooc_App.cours'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(help_text='Answer Text', max_length=2000)),
                ('question', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Isimmmooc_App.question')),
            ],
            options={
                'ordering': ['-answer_text'],
            },
        ),
    ]
