# Generated by Django 4.1.2 on 2023-01-19 13:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=None, help_text='Question relative', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Isimmmooc_App.question'),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='cours',
            field=models.ForeignKey(default=None, help_text='Cours associe', on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to='Isimmmooc_App.cours'),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='video',
            field=models.FileField(help_text='Video du chapitre', null=True, upload_to='Chapitre_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='cours',
            name='short_video',
            field=models.FileField(help_text='Short Video du Cours', null=True, upload_to='Cours_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='question',
            name='chapitre',
            field=models.OneToOneField(default=None, help_text='Chapitre associe', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Isimmmooc_App.chapitre'),
        ),
        migrations.DeleteModel(
            name='ChapitreVideo',
        ),
        migrations.DeleteModel(
            name='CoursVideo',
        ),
    ]
