# Generated by Django 4.1.2 on 2023-01-22 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Isimmmooc_App', '0001_initial'),
        ('Isimmmooc_Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='formateur',
            field=models.ForeignKey(default=None, help_text='Formateur du Cours', on_delete=django.db.models.deletion.CASCADE, to='Isimmmooc_Users.formateur'),
        ),
        migrations.AddField(
            model_name='chapitre',
            name='cours',
            field=models.ForeignKey(default=None, help_text='Cours associe', on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to='Isimmmooc_App.cours'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=None, help_text='Question relative', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Isimmmooc_App.question'),
        ),
    ]
