# Generated by Django 4.1.2 on 2022-10-19 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ville',
        ),
    ]
