# Generated by Django 4.1.2 on 2022-11-22 10:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0006_apprenant_user_comite_user_formateur_user_and_more'),
        ('Isimmmooc_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='difficulte',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
        migrations.AddField(
            model_name='cours',
            name='difficulty',
            field=models.CharField(choices=[('BG', 'Beginner'), ('MD', 'Intermediate'), ('AV', 'Advanced')], default='BG', help_text='Difficulte du chapitre', max_length=2),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=django.db.models.deletion.SET_NULL, help_text='Question relative', on_delete=django.db.models.deletion.CASCADE, to='Isimmmooc_App.question'),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='cours',
            field=models.ForeignKey(default='', help_text='Cours associe', on_delete=django.db.models.deletion.CASCADE, to='Isimmmooc_App.cours'),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='presentation',
            field=models.TextField(default='Chapitre Presentation', help_text='Presentation du chapitre', max_length=2000),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='video',
            field=models.FileField(help_text='Video du chapitre', null=True, upload_to='videos_uploaded/Chapitres', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='cours',
            name='description',
            field=models.TextField(default=django.db.models.deletion.SET_NULL, help_text='Description du Cours', max_length=2000),
        ),
        migrations.AlterField(
            model_name='cours',
            name='discipline',
            field=models.ForeignKey(default='', help_text='Discipline du Cours', on_delete=django.db.models.deletion.CASCADE, to='Isimmmooc_App.discipline'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='formateur',
            field=models.ForeignKey(default='', help_text='Formateur du Cours', on_delete=django.db.models.deletion.CASCADE, to='Isimmmooc_Users.formateur'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='period',
            field=models.FloatField(default=1, help_text='Periode du Cours(en Heure)'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='short_video',
            field=models.FileField(help_text='Short Video du Cours', null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='question',
            name='chapitre',
            field=models.OneToOneField(default=django.db.models.deletion.SET_NULL, help_text='Chapitre associe', on_delete=django.db.models.deletion.CASCADE, to='Isimmmooc_App.chapitre'),
        ),
        migrations.AlterField(
            model_name='question',
            name='number_options',
            field=models.IntegerField(help_text='Nombre d option', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(help_text='Question', max_length=2000),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('OC', 'One_Choice'), ('MC', 'Multiple_Choice')], default='OC', help_text='Type de Question', max_length=2),
        ),
    ]
