# Generated by Django 4.1.2 on 2022-10-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Isimmmooc_App', '0002_delete_ville'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de Cour', max_length=20)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
