# Generated by Django 4.1.2 on 2022-11-22 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0006_apprenant_user_comite_user_formateur_user_and_more'),
        ('Isimmmooc_App', '0002_remove_cours_difficulte_remove_question_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=None, help_text='Question relative', on_delete=django.db.models.deletion.CASCADE, to='Isimmmooc_App.question'),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='cours',
            field=models.ForeignKey(default=None, help_text='Cours associe', on_delete=django.db.models.deletion.CASCADE, to='Isimmmooc_App.cours'),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='presentation',
            field=models.TextField(default=None, help_text='Presentation du chapitre', max_length=2000),
        ),
        migrations.AlterField(
            model_name='cours',
            name='description',
            field=models.TextField(default=None, help_text='Description du Cours', max_length=2000),
        ),
        migrations.AlterField(
            model_name='cours',
            name='discipline',
            field=models.ForeignKey(default=None, help_text='Discipline du Cours', on_delete=django.db.models.deletion.CASCADE, to='Isimmmooc_App.discipline'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='formateur',
            field=models.ForeignKey(default=None, help_text='Formateur du Cours', on_delete=django.db.models.deletion.CASCADE, to='Isimmmooc_Users.formateur'),
        ),
        migrations.AlterField(
            model_name='question',
            name='chapitre',
            field=models.OneToOneField(default=None, help_text='Chapitre associe', on_delete=django.db.models.deletion.CASCADE, to='Isimmmooc_App.chapitre'),
        ),
    ]
