# Generated by Django 4.1.2 on 2023-01-15 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_App', '0002_alter_chapitre_video_alter_cours_short_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChapitreVideo',
        ),
        migrations.DeleteModel(
            name='CoursVideo',
        ),
    ]
