# Generated by Django 4.1.2 on 2022-10-24 22:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_App', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cour',
            options={},
        ),
        migrations.AddField(
            model_name='cour',
            name='description',
            field=models.TextField(default=models.CharField(help_text='Nom de Cour', max_length=50), max_length=1000),
        ),
        migrations.AddField(
            model_name='cour',
            name='short_video',
            field=models.FileField(null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='cour',
            name='name',
            field=models.CharField(help_text='Nom de Cour', max_length=50),
        ),
    ]
