# Generated by Django 4.1.2 on 2022-10-24 22:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_App', '0004_alter_cour_options_cour_description_cour_short_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de Cours', max_length=50)),
                ('short_video', models.FileField(null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('description', models.TextField(default='Cours Description', max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Cour',
        ),
    ]
