# Generated by Django 4.1.2 on 2023-01-18 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_App', '0004_answer_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=None, help_text='Question relative', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Isimmmooc_App.question'),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='cours',
            field=models.ForeignKey(default=None, help_text='Cours associe', on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to='Isimmmooc_App.cours'),
        ),
        migrations.AlterField(
            model_name='question',
            name='chapitre',
            field=models.OneToOneField(default=None, help_text='Chapitre associe', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Isimmmooc_App.chapitre'),
        ),
    ]
