# Generated by Django 4.1.2 on 2022-10-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_App', '0005_cours_delete_cour'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='difficulte',
            field=models.CharField(choices=[('BG', 'Beginner'), ('MD', 'Intermediate'), ('AV', 'Advanced')], default='BG', max_length=2),
        ),
        migrations.AddField(
            model_name='cours',
            name='periode',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='cours',
            name='name',
            field=models.CharField(help_text='Nom de Cours', max_length=100),
        ),
    ]
