# Generated by Django 4.1.2 on 2022-10-24 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0003_organisme'),
        ('Isimmmooc_App', '0006_cours_difficulte_cours_periode_alter_cours_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='formateur',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Isimmmooc_Users.formateur'),
        ),
    ]
