# Generated by Django 4.1.2 on 2022-10-24 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_App', '0007_cours_formateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du discipline', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cours',
            name='discipline',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Isimmmooc_App.discipline'),
        ),
    ]
