# Generated by Django 4.1.2 on 2022-10-24 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_App', '0008_discipline_cours_discipline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='discipline',
        ),
        migrations.DeleteModel(
            name='Discipline',
        ),
    ]
