# Generated by Django 4.1.2 on 2022-10-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_App', '0009_remove_cours_discipline_delete_discipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du discipline', max_length=100)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
