# Generated by Django 4.1.2 on 2022-10-24 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_App', '0010_discipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='discipline',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Isimmmooc_App.discipline'),
        ),
    ]
