# Generated by Django 4.1.2 on 2022-10-25 11:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_App', '0011_cours_discipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Titre du chapitre', max_length=200)),
                ('video', models.FileField(null=True, upload_to='videos_uploaded/Chapitres', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('presentation', models.TextField(default='Chapitre Presentation', max_length=2000)),
            ],
            options={
                'ordering': ['-titre'],
            },
        ),
        migrations.AlterField(
            model_name='cours',
            name='description',
            field=models.TextField(default='Cours Description', max_length=2000),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(default='Question Text', max_length=2000)),
                ('number_options', models.IntegerField(max_length=5)),
                ('type', models.CharField(choices=[('OC', 'One_Choice'), ('MC', 'Multiple_Choice')], default='OC', max_length=2)),
                ('chapitre', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Isimmmooc_App.chapitre')),
            ],
            options={
                'ordering': ['-question_text'],
            },
        ),
    ]
