# Generated by Django 4.1.2 on 2022-10-25 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_App', '0012_chapitre_alter_cours_description_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='number_options',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
