# Generated by Django 4.1.2 on 2022-10-27 19:45

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_App', '0013_alter_question_number_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Item title 2.1'), (2, 'Item title 2.2'), (3, 'Item title 2.3'), (4, 'Item title 2.4'), (5, 'Item title 2.5')], default=1, max_length=3),
        ),
    ]
