# Generated by Django 4.1.2 on 2022-10-27 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_App', '0014_question_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
    ]
