# Generated by Django 4.1.2 on 2022-11-22 10:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nom de l Organisme', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Email de l Organisme', max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Numero de telephone de l Organisme', max_length=128, region=None)),
                ('web_site', models.URLField(blank=True, help_text='Web Site de l Organisme')),
                ('file_exist', models.FileField(blank=True, help_text='File Exist de l Organisme', upload_to='Uploaded_files/Organisme_files')),
                ('adress', models.CharField(help_text='Adresse de l Organisme', max_length=200)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='PreOrganisme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de Organisme', max_length=20)),
                ('cours_category', models.CharField(max_length=36)),
                ('email', models.EmailField(max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('web_site', models.URLField()),
                ('adresse', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='PreFormateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Nom de Formateur', max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('date_of_birth', models.DateField(blank=True, default=datetime.datetime.now)),
                ('mail', models.EmailField(blank=True, default='', max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None)),
                ('cv', models.FileField(blank=True, upload_to='')),
                ('accepted', models.BooleanField()),
                ('organisme', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Isimmmooc_Users.organisme')),
            ],
            options={
                'ordering': ['-first_name'],
            },
        ),
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Prenom de Formateur', max_length=20)),
                ('last_name', models.CharField(blank=True, help_text='Nom de Formateur', max_length=30)),
                ('date_of_birth', models.DateField(blank=True, default=datetime.datetime(2001, 12, 26, 0, 0), help_text='Date de naissance de Formateur')),
                ('mail', models.EmailField(blank=True, default=None, help_text='Email de Formateur', max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, help_text='Numero de telephone de Formateur', max_length=128, region=None)),
                ('cv', models.FileField(blank=True, help_text='CV de Formateur', upload_to='')),
                ('organisme', models.ForeignKey(default=None, help_text='Organisme de Formateur(si existe)', null=True, on_delete=django.db.models.deletion.CASCADE, to='Isimmmooc_Users.organisme')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-first_name'],
            },
        ),
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, help_text='Prenom du Comite', max_length=255)),
                ('last_name', models.CharField(default=None, help_text='Nom du Comite', max_length=255)),
                ('grade', models.CharField(blank=True, help_text='Niveau du Comite', max_length=255)),
                ('department', models.CharField(default=None, help_text='Departement du Comite', max_length=255)),
                ('email', models.EmailField(blank=True, help_text='Email du Comite', max_length=255, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default=None, help_text='Numero de telephone du Comite', max_length=12, region=None, unique=True)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-phone_number'],
            },
        ),
        migrations.CreateModel(
            name='Apprenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Prenom de l Apprenant', max_length=20)),
                ('last_name', models.CharField(blank=True, help_text='Nom de l Apprenant', max_length=30)),
                ('date_of_birth', models.DateField(blank=True, default=datetime.datetime(2001, 12, 26, 0, 0), help_text='Date de naissance de l Apprenant')),
                ('mail', models.EmailField(blank=True, default=None, help_text='Email de l Apprenant', max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, help_text='Numero de Telephone de l Apprenant', max_length=128, region=None)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-first_name'],
            },
        ),
    ]
