# Generated by Django 4.1.2 on 2022-11-18 21:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apprenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Nom de l Apprenant', max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('date_of_birth', models.DateField(blank=True, default=datetime.datetime.now)),
                ('mail', models.EmailField(blank=True, default='', max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None)),
            ],
            options={
                'ordering': ['-first_name'],
            },
        ),
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Comite first name', max_length=255)),
                ('last_name', models.CharField(default='Comite last name', max_length=255)),
                ('grade', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(default='Comite Department', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=12, region=None, unique=True)),
            ],
            options={
                'ordering': ['-phone_number'],
            },
        ),
        migrations.CreateModel(
            name='Organisme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nom de Organisme', max_length=20)),
                ('cours_category', models.CharField(blank=True, max_length=36)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('password', models.CharField(blank=True, max_length=32)),
                ('web_site', models.URLField(blank=True)),
                ('file_exist', models.FileField(blank=True, upload_to='')),
                ('adresse', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='PreOrganisme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nom de Organisme', max_length=20)),
                ('cours_category', models.CharField(blank=True, max_length=36)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('password', models.CharField(blank=True, max_length=32)),
                ('web_site', models.URLField(blank=True)),
                ('adresse', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Nom de Formateur', max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('date_of_birth', models.DateField(blank=True, default=datetime.datetime.now)),
                ('mail', models.EmailField(blank=True, default=datetime.datetime.now, max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None)),
                ('cv', models.FileField(blank=True, upload_to='')),
                ('organisme', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Isimmmooc_Users.organisme')),
            ],
            options={
                'ordering': ['-first_name'],
            },
        ),
    ]
