# Generated by Django 4.1.2 on 2022-10-30 10:56

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Comite first name', max_length=255)),
                ('last_name', models.CharField(default='Comite last name', max_length=255)),
                ('grade', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(default='Comite Department', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=12, region=None, unique=True)),
            ],
            options={
                'ordering': ['-phone_number'],
            },
        ),
    ]
