# Generated by Django 4.1.2 on 2023-01-17 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comite',
            options={'ordering': ['-last_name']},
        ),
    ]
