# Generated by Django 4.1.2 on 2022-11-01 11:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formateur',
            options={'ordering': ['-first_name']},
        ),
        migrations.RenameField(
            model_name='formateur',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='formateur',
            name='cv',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='formateur',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='formateur',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='formateur',
            name='mail',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='formateur',
            name='organisme',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Isimmmooc_Users.organisme'),
        ),
        migrations.AddField(
            model_name='formateur',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None),
        ),
    ]
