# Generated by Django 4.1.2 on 2022-11-18 21:33

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprenant',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='apprenant',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='apprenant',
            name='mail',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='apprenant',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='comite',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='comite',
            name='grade',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='formateur',
            name='cv',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='formateur',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='formateur',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='formateur',
            name='mail',
            field=models.EmailField(default=datetime.datetime.now, max_length=254),
        ),
        migrations.AlterField(
            model_name='formateur',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='organisme',
            name='adresse',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='organisme',
            name='cours_category',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='organisme',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='organisme',
            name='file_exist',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='organisme',
            name='name',
            field=models.CharField(help_text='Nom de Organisme', max_length=20),
        ),
        migrations.AlterField(
            model_name='organisme',
            name='password',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='organisme',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='organisme',
            name='web_site',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='preorganisme',
            name='adresse',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='preorganisme',
            name='cours_category',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='preorganisme',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='preorganisme',
            name='name',
            field=models.CharField(help_text='Nom de Organisme', max_length=20),
        ),
        migrations.AlterField(
            model_name='preorganisme',
            name='password',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='preorganisme',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='preorganisme',
            name='web_site',
            field=models.URLField(),
        ),
    ]
