# Generated by Django 4.1.2 on 2023-01-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comite',
            options={'ordering': ['-last_name']},
        ),
        migrations.AddField(
            model_name='formateur',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Formateur/'),
        ),
        migrations.AddField(
            model_name='preformateur',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='PreFormateur/'),
        ),
    ]
