# Generated by Django 4.1.2 on 2023-01-19 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0002_alter_comite_options'),
        ('Isimmmooc_Users', '0002_alter_comite_options_formateur_image_and_more'),
    ]

    operations = [
    ]
