# Generated by Django 4.1.2 on 2022-11-01 11:56

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0002_alter_formateur_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apprenant',
            options={'ordering': ['-first_name']},
        ),
        migrations.RenameField(
            model_name='apprenant',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='apprenant',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='apprenant',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='apprenant',
            name='mail',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='apprenant',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='formateur',
            name='mail',
            field=models.EmailField(blank=True, default=datetime.datetime.now, max_length=254),
        ),
    ]
