# Generated by Django 4.1.2 on 2022-10-20 22:20

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0002_comite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nom de Organisme', max_length=20)),
                ('categorie_cours', models.CharField(blank=True, max_length=36)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('password', models.CharField(blank=True, max_length=32)),
                ('site_web', models.URLField(blank=True)),
                ('file_exist', models.FileField(blank=True, upload_to='')),
            ],
            options={
                'ordering': ['-file_exist'],
                'ordering' : ['-name'],
                'ordering' : ['-categorie_cours'],
                'ordering ': ['-email'],
                'ordering' : ['-phone_number'],
                'ordering' : ['-password'],
                'ordering' : ['-site_web'],
            },
        ),
    ]
