# Generated by Django 4.1.2 on 2022-11-20 19:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0002_remove_organisme_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreFormateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Nom de Formateur', max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('date_of_birth', models.DateField(blank=True, default=datetime.datetime.now)),
                ('mail', models.EmailField(blank=True, default='', max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None)),
                ('cv', models.FileField(blank=True, upload_to='')),
                ('accepted', models.BooleanField()),
                ('organisme', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Isimmmooc_Users.organisme')),
            ],
            options={
                'ordering': ['-first_name'],
            },
        ),
    ]
