# Generated by Django 4.1.2 on 2022-11-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0003_alter_apprenant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formateur',
            name='mail',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
