# Generated by Django 4.1.2 on 2022-10-28 23:30

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0003_organisme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comite',
            options={},
        ),
        migrations.AddField(
            model_name='comite',
            name='Email',
            field=models.EmailField(blank=True, max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='comite',
            name='departement',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='comite',
            name='grade',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='comite',
            name='password',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='comite',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='454555', max_length=8, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='comite',
            name='prenom',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AlterField(
            model_name='comite',
            name='name',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AddConstraint(
            model_name='comite',
            constraint=models.CheckConstraint(check=models.Q(('phone__length__gte', 8)), name='isimmmooc_users_comite_title_length'),
        ),
    ]
