# Generated by Django 4.1.2 on 2022-10-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0004_alter_comite_options_comite_email_comite_departement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formateur',
            name='prenom',
            field=models.CharField(blank=True, default='a ', max_length=30),
        ),
    ]
