# Generated by Django 4.1.2 on 2022-11-19 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0004_alter_formateur_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisme',
            name='cours_category',
        ),
        migrations.RemoveField(
            model_name='organisme',
            name='password',
        ),
    ]
