# Generated by Django 4.1.2 on 2022-10-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0005_formateur_prenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='formateur',
            name='date_de_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
