# Generated by Django 4.1.2 on 2022-11-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0007_alter_apprenant_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisme',
            name='file_exist',
            field=models.FileField(blank=True, help_text='File Exist de l Organisme', upload_to='Uploaded_files/Organisme_files'),
        ),
    ]
