# Generated by Django 4.1.2 on 2022-10-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0007_formateur_address_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='formateur',
            name='phone_number',
            field=models.CharField(blank=True, default='a ', max_length=20, null=True),
        ),
    ]
