# Generated by Django 4.1.2 on 2022-10-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0009_formateur_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='formateur',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
