# Generated by Django 4.1.2 on 2022-10-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0010_formateur_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprenant',
            name='prenom',
            field=models.CharField(blank=True, default='a ', max_length=30),
        ),
    ]
