# Generated by Django 4.1.2 on 2022-10-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0011_apprenant_prenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprenant',
            name='date_de_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
