# Generated by Django 4.1.2 on 2022-10-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0015_apprenant_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormateurEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de l Apprenant', max_length=20)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
