# Generated by Django 4.1.2 on 2022-10-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0020_formateurentreprise_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='formateurentreprise',
            name='password',
            field=models.CharField(blank=True, default=' a', max_length=20, null=True),
        ),
    ]
