# Generated by Django 4.1.2 on 2022-10-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0022_formateurentreprise_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='formateurentreprise',
            name='nom_entreprise',
            field=models.CharField(blank=True, default=' a', max_length=10, null=True),
        ),
    ]
