# Generated by Django 4.1.2 on 2022-10-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0023_formateurentreprise_nom_entreprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprenant',
            name='date_de_naissance',
            field=models.DateField(blank=True),
        ),
    ]
