# Generated by Django 4.1.2 on 2022-10-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0024_alter_apprenant_date_de_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprenant',
            name='address_mail',
            field=models.EmailField(blank=True, default=' a', max_length=254),
        ),
    ]
