# Generated by Django 4.1.2 on 2022-10-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0025_alter_apprenant_address_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprenant',
            name='phone_number',
            field=models.CharField(blank=True, default='a ', max_length=20),
        ),
    ]
