# Generated by Django 4.1.2 on 2022-10-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0030_alter_formateur_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formateur',
            name='password',
            field=models.CharField(blank=True, default=' a', max_length=20),
        ),
    ]
