# Generated by Django 4.1.2 on 2022-10-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0031_alter_formateur_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formateurentreprise',
            name='date_de_naissance',
            field=models.DateField(blank=True),
        ),
    ]
