# Generated by Django 4.1.2 on 2022-10-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0035_alter_formateurentreprise_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formateurentreprise',
            name='nom_entreprise',
            field=models.CharField(blank=True, default=' a', max_length=10),
        ),
    ]
