# Generated by Django 4.1.2 on 2022-10-29 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Isimmmooc_Users', '0038_alter_formateur_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formateurentreprise',
            name='password',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
