# Generated by Django 4.1.2 on 2022-10-29 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0039_alter_formateurentreprise_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprenant',
            name='prenom',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
