# Generated by Django 4.1.2 on 2022-10-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0040_alter_apprenant_prenom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprenant',
            name='address_mail',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
