# Generated by Django 4.1.2 on 2022-10-29 00:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0042_alter_apprenant_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprenant',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
