# Generated by Django 4.1.2 on 2022-10-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0043_alter_apprenant_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formateur',
            name='prenom',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
