# Generated by Django 4.1.2 on 2022-10-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0044_alter_formateur_prenom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formateur',
            name='address_mail',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
