# Generated by Django 4.1.2 on 2022-10-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0050_alter_formateurentreprise_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formateurentreprise',
            name='nom_entreprise',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
