# Generated by Django 4.1.2 on 2022-10-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0053_alter_comite_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='formateur',
            name='nom_entreprise',
            field=models.BooleanField(blank=True, max_length=10, null=True),
        ),
    ]
