# Generated by Django 4.1.2 on 2022-10-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0054_formateur_nom_entreprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formateur',
            name='cv',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
