# Generated by Django 4.1.2 on 2022-10-29 15:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Isimmmooc_Users', '0055_alter_formateur_cv'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormateurEntreprise',
            new_name='Pre_Formateur',
        ),
    ]
