# Generated by Django 4.1.2 on 2022-10-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Isimmmooc_Users', '0057_alter_pre_formateur_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formateur',
            name='nom_entreprise',
        ),
        migrations.AddField(
            model_name='formateur',
            name='nom_entreprise',
            field=models.ManyToManyField(default='', null=True, to='Isimmmooc_Users.organisme'),
        ),
    ]
