# Generated by Django 4.1.2 on 2022-10-30 11:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Isimmmooc_Users', '0059_remove_pre_formateur_nom_entreprise_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pre_Formateur',
            new_name='PreFormateur',
        ),
    ]
