from .CoursSerializer import CoursSerializer
from .ChapitreSerializer import ChapitreSerializer
from .DisciplineSerializer import DisciplineSerializer
from .AnswerSerializer import AnswerSerializer
from .QuestionSerializer import QuestionSerializer
from .CoursFullSerializer import CoursFullSerializer
from .ChapitreFullSerializer import ChapitreFullSerializer
from .QuestionFullSerializer import QuestionFullSerializer